version: '3.1'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      BACKEND_DNS: backend
      BACKEND_PORT: 9000
    ports:
      - 8085:8080
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      REDIS_DNS: redis
    depends_on:
      - redis

  redis:
    container_name: redis
    command: redis-server --appendonly yes
    image: redis:latest
    expose: 
      - 6379
    volumes:
        - ./redis-volume:/data

