version: '3.1'

services:
  frontend_container:
    image: frontend
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_HOST: mysql-container
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - mysql_container
  
  redis:
    image: redis:latest
