name: pipeline
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-step
        uses: actions/checkout@v3
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

  Test:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: test-step
        run: cd backend && go test -v