name: pipeline
on: push
jobs:
  Clone-down:
    runs-on: self-hosted
    steps:
      - name: checkout-step
        uses: actions/checkout@v1
      - name: Upload Repo
        uses: actions/upload-artifact@v1
        with:
          name: code
          path: .

  Test:
    runs-on: self-hosted
    needs: Clone-down
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - name: test-step
        run: cd backend && go test -v